import LayoutProvider from '@/components/LayoutProvider'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Task Manager',
  description: 'Generated by create next app',
}

const RootLayout = ({ children, }: { children: React.ReactNode }) => {
  return (
    <LayoutProvider>
      {children}
    </LayoutProvider>
  )
};

export default RootLayout;
