import LayoutProvider from '@/components/LayoutProvider'
import type { Metadata } from 'next'
import './globals.css'
import ReduxProvider from '@/components/ReduxProvider'

export const metadata: Metadata = {
  title: 'Task Manager',
  description: 'Generated by create next app',
}

const RootLayout = ({ children, }: { children: React.ReactNode }) => {
  return (
    <ReduxProvider>
      <LayoutProvider>
        {children}
      </LayoutProvider>
    </ReduxProvider>
  )
};

export default RootLayout;
