import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import ReduxProvider from '@/components/ReduxProvider';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Redux with Next',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <ReduxProvider>
      {children}
    </ReduxProvider>
  )
}